on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.5.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:5187/bookstore?bookid=65&isloggedin=true'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
